# Generated by Django 5.2 on 2025-04-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='item',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='item',
            name='background_color',
            field=models.CharField(default='#f0f0f0', max_length=7),
        ),
        migrations.AddField(
            model_name='item',
            name='eyebrow',
            field=models.CharField(default='eyebrow1.png', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='eyes',
            field=models.CharField(default='eye1.png', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='hair',
            field=models.CharField(default='hair1.png', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='head',
            field=models.CharField(default='face1.png', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='mouth',
            field=models.CharField(default='mouth1.png', max_length=100),
        ),
    ]
